# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Dash',
                'doc_host': 'https://Solab5.github.io',
                'git_url': 'https://github.com/Solab5/Dash',
                'lib_path': 'Dash'},
  'syms': { 'Dash.dash': { 'Dash.dash.audience_simple': ('dash.html#audience_simple', 'Dash/dash.py'),
                           'Dash.dash.load_data': ('dash.html#load_data', 'Dash/dash.py'),
                           'Dash.dash.style_negative': ('dash.html#style_negative', 'Dash/dash.py'),
                           'Dash.dash.style_positive': ('dash.html#style_positive', 'Dash/dash.py')}}}
